version: '2.1'
services:
  mongo:
    image: 'mongo:3.6.8'
    container_name: 'mongodb-local'
    environment:
      - MONGO_INITDB_ROOT_NAME=mongodb-local
      - MONGO_INITDB_ROOT_USERNAME=productListUser
      - MONGO_INITDB_ROOT_PASSWORD=productListPassword
    volumes:
      - ../products-db/database:/data/db
    ports:
      - '27017:27017'